<?php

/*
**  This is a more common and useful version of a page on the site. Here, we include a special _videos_header.html
**  file, which allows us to specify the exact IDs and classes we want for our document. Then, the content within,
**  although hard coded here, would like be generated by PHP on-the-fly.
*/
include_once ('session.php');

//include_once ('functions.php');
//include_once ('sqlfuncs.php');

include_once ('data.php');

include ('inc/_videos_header.html');

?>
    <div class="heading">
        <h3>Video Training Series</h3>
        <p>This video training series is all about the Sunsight AAT.</p>
    </div>
    
    <div class="content">

<?php

function embedVideo($vimeoID)
{
    print("
                <div class=\"embed-responsive embed-responsive-16by9\">\r\n
                    <iframe src=\"https://player.vimeo.com/video/$vimeoID\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>\r\n
                </div>\r\n"
    );
}

    /*
    **  When the hyperlinks are written below, the variable "videoid" is passed via the URL string,
    **  which will tell us which video should be displayed in the player.
    */

    $curVideo = $_GET["videoid"];
    $videoList = getVideoList();

    if (! IsSet($curVideo) || $curVideo > $videoList->totalVideos()-1) $curVideo = 0;

    print("<div class=\"currentVideo\">\r\n");
        print("<h4>" . $videoList->getVideo($curVideo)->getTitle() . "</h4>\r\n");
        embedVideo($videoList->getVideo($curVideo)->getID());
        print("<div class=\"videoLinks\">\r\n");
            $previous = $curVideo - 1;
            $prevLink = "<a href=\"videos.php?videoid=$previous\">Prev</a>";

            if( $previous < 0 ) $prevLink = "Previous";
            print("<span class=\"linkPrev\">$prevLink</span>\r\n");

            $next = $curVideo + 1;
            $nextLink = "<a href=\"videos.php?videoid=$next\">Next</a>";

            if( $next >= $videoList->totalVideos() ) $nextLink = "Next";
            print("<span class=\"linkNext\">$nextLink</span>\r\n");
        print("</div>\r\n");
    print("</div>\r\n");

    $curCollection = "";
    
    for( $start = 0; $start < $videoList->totalVideos(); ++$start ){
        $vid = $videoList->getNextVideo($start);
        
        if( $curCollection != $vid->getCollection() ){
            if ($curCollection != '') print("</ul></div>\r\n");
            print("<div class=\"vid-collection\">\r\n");
            print("<h4>" . $vid->getCollection() . "</h4>\r\n");
            $curCollection = $vid->getCollection();
            print("<ul>\r\n");
        }
        
        print("<li><a href=\"videos.php?videoid=$start\">" . $vid->getTitle() . "</a></li>\r\n");
    }
    print("</ul></div>\r\n");
?>
    </div><!--  class="content" -->
<?php

include ('inc/_def_footer.html');


/*
function cbIterate(cVideo $vid)
{
	print($vid->getTitle() . "<br />\r\n");
}

foreachVideo('cbIterate');
*/



?>
